export const keyStyles = {
  key: {
    height: 150,
    width: 260,
    opacity: 0.045,
    alignSelf: 'center',
    marginTop: 26,
    marginBottom: 24,
    position: 'relative',
  },
  smallKey: {
    height: 110,
    marginVertical: 10,
    transform: [{ scale: 0.86 }],
  },
  keyCircle: {
    position: 'absolute',
    width: 116,
    height: 116,
    borderRadius: 58,
    borderWidth: 24,
    borderColor: '#061125',
    left: 0,
    top: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  keyHole: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#061125',
  },
  keyStem: {
    position: 'absolute',
    height: 28,
    width: 145,
    backgroundColor: '#061125',
    left: 100,
    top: 70,
  },
  keyToothOne: {
    position: 'absolute',
    width: 46,
    height: 46,
    backgroundColor: '#061125',
    left: 170,
    top: 84,
    transform: [{ rotate: '45deg' }],
  },
  keyToothTwo: {
    position: 'absolute',
    width: 52,
    height: 52,
    backgroundColor: '#061125',
    left: 218,
    top: 62,
    transform: [{ rotate: '45deg' }],
  },
};