USE subastas;

INSERT INTO paises (numero, capital, idiomas, nacionalidad, nombre, nombre_corto) VALUES
(4, 'Kabul', 'pastún, dari', 'afgana', 'Afganistán', 'AF'),
(8, 'Tirana', 'albanés', 'albanesa', 'Albania', 'AL'),
(12, 'Argel', 'árabe, tamazight', 'argelina', 'Argelia', 'DZ'),
(20, 'Andorra la Vieja', 'catalán', 'andorrana', 'Andorra', 'AD'),
(24, 'Luanda', 'portugués', 'angoleña', 'Angola', 'AO'),
(32, 'Buenos Aires', 'español', 'argentina', 'Argentina', 'AR'),
(36, 'Canberra', 'inglés', 'australiana', 'Australia', 'AU'),
(40, 'Viena', 'alemán', 'austriaca', 'Austria', 'AT'),
(44, 'Nasáu', 'inglés', 'bahameña', 'Bahamas', 'BS'),
(48, 'Manama', 'árabe', 'bareiní', 'Baréin', 'BH'),
(50, 'Daca', 'bengalí', 'bangladesí', 'Bangladés', 'BD'),
(52, 'Bridgetown', 'inglés', 'barbadense', 'Barbados', 'BB'),
(56, 'Bruselas', 'neerlandés, francés, alemán', 'belga', 'Bélgica', 'BE'),
(68, 'Sucre', 'español, quechua, aimara, guaraní', 'boliviana', 'Bolivia', 'BO'),
(70, 'Sarajevo', 'bosnio, croata, serbio', 'bosnia', 'Bosnia y Herzegovina', 'BA'),
(76, 'Brasilia', 'portugués', 'brasileña', 'Brasil', 'BR'),
(84, 'Belmopán', 'inglés', 'beliceña', 'Belice', 'BZ'),
(100, 'Sofía', 'búlgaro', 'búlgara', 'Bulgaria', 'BG'),
(124, 'Ottawa', 'inglés, francés', 'canadiense', 'Canadá', 'CA'),
(152, 'Santiago', 'español', 'chilena', 'Chile', 'CL'),
(156, 'Pekín', 'chino mandarín', 'china', 'China', 'CN'),
(170, 'Bogotá', 'español', 'colombiana', 'Colombia', 'CO'),
(188, 'San José', 'español', 'costarricense', 'Costa Rica', 'CR'),
(191, 'Zagreb', 'croata', 'croata', 'Croacia', 'HR'),
(192, 'La Habana', 'español', 'cubana', 'Cuba', 'CU'),
(203, 'Praga', 'checo', 'checa', 'Chequia', 'CZ'),
(208, 'Copenhague', 'danés', 'danesa', 'Dinamarca', 'DK'),
(214, 'Santo Domingo', 'español', 'dominicana', 'República Dominicana', 'DO'),
(218, 'Quito', 'español', 'ecuatoriana', 'Ecuador', 'EC'),
(222, 'San Salvador', 'español', 'salvadoreña', 'El Salvador', 'SV'),
(233, 'Tallin', 'estonio', 'estonia', 'Estonia', 'EE'),
(246, 'Helsinki', 'finés, sueco', 'finlandesa', 'Finlandia', 'FI'),
(250, 'París', 'francés', 'francesa', 'Francia', 'FR'),
(276, 'Berlín', 'alemán', 'alemana', 'Alemania', 'DE'),
(300, 'Atenas', 'griego', 'griega', 'Grecia', 'GR'),
(320, 'Ciudad de Guatemala', 'español', 'guatemalteca', 'Guatemala', 'GT'),
(340, 'Tegucigalpa', 'español', 'hondureña', 'Honduras', 'HN'),
(348, 'Budapest', 'húngaro', 'húngara', 'Hungría', 'HU'),
(352, 'Reikiavik', 'islandés', 'islandesa', 'Islandia', 'IS'),
(356, 'Nueva Delhi', 'hindi, inglés', 'india', 'India', 'IN'),
(360, 'Yakarta', 'indonesio', 'indonesia', 'Indonesia', 'ID'),
(364, 'Teherán', 'persa', 'iraní', 'Irán', 'IR'),
(368, 'Bagdad', 'árabe, kurdo', 'iraquí', 'Irak', 'IQ'),
(372, 'Dublín', 'irlandés, inglés', 'irlandesa', 'Irlanda', 'IE'),
(376, 'Jerusalén', 'hebreo', 'israelí', 'Israel', 'IL'),
(380, 'Roma', 'italiano', 'italiana', 'Italia', 'IT'),
(392, 'Tokio', 'japonés', 'japonesa', 'Japón', 'JP'),
(400, 'Amán', 'árabe', 'jordana', 'Jordania', 'JO'),
(410, 'Seúl', 'coreano', 'surcoreana', 'Corea del Sur', 'KR'),
(414, 'Kuwait', 'árabe', 'kuwaití', 'Kuwait', 'KW'),
(422, 'Beirut', 'árabe', 'libanesa', 'Líbano', 'LB'),
(428, 'Riga', 'letón', 'letona', 'Letonia', 'LV'),
(440, 'Vilna', 'lituano', 'lituana', 'Lituania', 'LT'),
(442, 'Luxemburgo', 'luxemburgués, francés, alemán', 'luxemburguesa', 'Luxemburgo', 'LU'),
(458, 'Kuala Lumpur', 'malayo', 'malasia', 'Malasia', 'MY'),
(470, 'La Valeta', 'maltés, inglés', 'maltesa', 'Malta', 'MT'),
(484, 'Ciudad de México', 'español', 'mexicana', 'México', 'MX'),
(504, 'Rabat', 'árabe, tamazight', 'marroquí', 'Marruecos', 'MA'),
(528, 'Ámsterdam', 'neerlandés', 'neerlandesa', 'Países Bajos', 'NL'),
(554, 'Wellington', 'inglés, maorí', 'neozelandesa', 'Nueva Zelanda', 'NZ'),
(558, 'Managua', 'español', 'nicaragüense', 'Nicaragua', 'NI'),
(566, 'Abuya', 'inglés', 'nigeriana', 'Nigeria', 'NG'),
(578, 'Oslo', 'noruego', 'noruega', 'Noruega', 'NO'),
(586, 'Islamabad', 'urdu, inglés', 'pakistaní', 'Pakistán', 'PK'),
(591, 'Ciudad de Panamá', 'español', 'panameña', 'Panamá', 'PA'),
(600, 'Asunción', 'español, guaraní', 'paraguaya', 'Paraguay', 'PY'),
(604, 'Lima', 'español, quechua, aimara', 'peruana', 'Perú', 'PE'),
(608, 'Manila', 'filipino, inglés', 'filipina', 'Filipinas', 'PH'),
(616, 'Varsovia', 'polaco', 'polaca', 'Polonia', 'PL'),
(620, 'Lisboa', 'portugués', 'portuguesa', 'Portugal', 'PT'),
(634, 'Doha', 'árabe', 'catarí', 'Catar', 'QA'),
(642, 'Bucarest', 'rumano', 'rumana', 'Rumania', 'RO'),
(643, 'Moscú', 'ruso', 'rusa', 'Rusia', 'RU'),
(682, 'Riad', 'árabe', 'saudí', 'Arabia Saudita', 'SA'),
(688, 'Belgrado', 'serbio', 'serbia', 'Serbia', 'RS'),
(702, 'Singapur', 'inglés, malayo, mandarín, tamil', 'singapurense', 'Singapur', 'SG'),
(703, 'Bratislava', 'eslovaco', 'eslovaca', 'Eslovaquia', 'SK'),
(704, 'Hanói', 'vietnamita', 'vietnamita', 'Vietnam', 'VN'),
(705, 'Liubliana', 'esloveno', 'eslovena', 'Eslovenia', 'SI'),
(710, 'Pretoria', 'zulú, xhosa, afrikáans, inglés', 'sudafricana', 'Sudáfrica', 'ZA'),
(724, 'Madrid', 'español', 'española', 'España', 'ES'),
(752, 'Estocolmo', 'sueco', 'sueca', 'Suecia', 'SE'),
(756, 'Berna', 'alemán, francés, italiano, romanche', 'suiza', 'Suiza', 'CH'),
(764, 'Bangkok', 'tailandés', 'tailandesa', 'Tailandia', 'TH'),
(780, 'Puerto España', 'inglés', 'trinitense', 'Trinidad y Tobago', 'TT'),
(784, 'Abu Dabi', 'árabe', 'emiratí', 'Emiratos Árabes Unidos', 'AE'),
(788, 'Túnez', 'árabe', 'tunecina', 'Túnez', 'TN'),
(792, 'Ankara', 'turco', 'turca', 'Turquía', 'TR'),
(804, 'Kiev', 'ucraniano', 'ucraniana', 'Ucrania', 'UA'),
(818, 'El Cairo', 'árabe', 'egipcia', 'Egipto', 'EG'),
(826, 'Londres', 'inglés', 'británica', 'Reino Unido', 'GB'),
(840, 'Washington D. C.', 'inglés', 'estadounidense', 'Estados Unidos', 'US'),
(858, 'Montevideo', 'español', 'uruguaya', 'Uruguay', 'UY'),
(862, 'Caracas', 'español', 'venezolana', 'Venezuela', 'VE');

SELECT * FROM paises;
