import { StyleSheet } from 'react-native';

import { palette } from '../constants/palette';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fbfbfc',
  },
  keyboard: {
    flex: 1,
  },
  emailScroll: {
    minHeight: '100%',
    paddingHorizontal: 23,
    paddingBottom: 36,
  },
  codeScroll: {
    minHeight: '100%',
    paddingHorizontal: 22,
    paddingBottom: 38,
  },
  passwordScroll: {
    minHeight: '100%',
    paddingHorizontal: 26,
    paddingBottom: 34,
  },
  topChrome: {
    height: 72,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 10,
  },
  topChromeCompact: {
    height: 120,
  },
  recoveryBackButton: {
    position: 'absolute',
    left: -12,
    top: 14,
    height: 42,
    width: 42,
    justifyContent: 'center',
  },
  recoveryBackIcon: {
    color: '#111316',
    fontSize: 28,
    fontWeight: '300',
    lineHeight: 31,
  },
  topLogo: {
    width: 98,
    height: 34,
  },
  logo: {
    width: 103,
    height: 44,
  },
  emailHero: {
    marginTop: 85,
  },
  kicker: {
    color: palette.gold,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 4,
    marginBottom: 14,
  },
  emailTitle: {
    color: '#030303',
    fontFamily: 'serif',
    fontSize: 37,
    fontWeight: '800',
    lineHeight: 41,
    marginBottom: 12,
  },
  emailSubtitle: {
    color: '#5f6570',
    fontSize: 16,
    lineHeight: 23,
    marginBottom: 34,
  },
  label: {
    color: '#8d929b',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  emailFieldGroup: {
    marginBottom: 36,
  },
  outlinedInput: {
    height: 50,
    borderWidth: 1,
    borderColor: '#d8dbe0',
    color: '#1e2530',
    fontSize: 16,
    paddingHorizontal: 0,
  },
  primaryButton: {
    height: 47,
    backgroundColor: palette.navy,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 1,
  },
  primaryText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 3.3,
  },
  feedback: {
    color: palette.danger,
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 14,
  },
  pressed: {
    opacity: 0.72,
  },
  trustFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 65,
    gap: 13,
  },
  footerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#e1e3e8',
  },
  footerCenter: {
    color: '#b1b4ba',
    fontSize: 8,
    letterSpacing: 0.7,
  },
  footerLinks: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 21,
  },
  footerLink: {
    color: '#9fa3aa',
    fontSize: 9,
  },
  codeContent: {
    marginTop: 44,
  },
  codeTitle: {
    color: '#030303',
    fontFamily: 'serif',
    fontSize: 32,
    fontWeight: '800',
    marginBottom: 14,
  },
  codeSubtitle: {
    color: '#5f6570',
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 37,
  },
  codeBoxes: {
    flexDirection: 'row',
    gap: 7,
    marginBottom: 37,
  },
  codeBox: {
    width: 38,
    height: 50,
    borderWidth: 1,
    borderColor: '#a7abb3',
    backgroundColor: '#f5f6f8',
    color: '#727987',
    fontSize: 24,
    fontWeight: '700',
  },
  resendBlock: {
    alignItems: 'center',
    marginTop: 20,
  },
  resendQuestion: {
    color: '#777d86',
    fontSize: 10,
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  resendLink: {
    color: palette.gold,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.5,
    textDecorationLine: 'underline',
    textDecorationColor: '#d3c09b',
  },
  protocolBlock: {
    alignItems: 'center',
    marginTop: 67,
  },
  protocolLine: {
    height: 42,
    width: 1,
    backgroundColor: '#d3b982',
    marginBottom: 27,
  },
  protocolDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#9b7d35',
    marginBottom: 16,
  },
  protocolText: {
    color: '#a8abb2',
    fontSize: 8,
    letterSpacing: 2.1,
  },
  passwordLogoWrap: {
    alignItems: 'center',
    paddingTop: 11,
  },
  passwordContent: {
    marginTop: 150,
  },
  passwordTitle: {
    color: '#030303',
    fontFamily: 'serif',
    fontSize: 27,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 10,
  },
  passwordSubtitle: {
    color: '#5f6570',
    fontSize: 12,
    lineHeight: 19,
    textAlign: 'center',
    marginBottom: 32,
  },
  passwordFieldGroup: {
    marginBottom: 18,
  },
  passwordInputShell: {
    height: 46,
    borderRadius: 4,
    backgroundColor: '#f0f0f2',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  passwordInput: {
    flex: 1,
    color: '#1d2330',
    fontSize: 14,
  },
  eyeButton: {
    width: 32,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyeText: {
    color: '#8a8f98',
    fontSize: 20,
  },
  matchText: {
    color: '#11a86f',
    fontSize: 11,
    marginTop: -8,
    marginBottom: 27,
  },
  passwordHint: {
    color: '#92969f',
    fontSize: 9,
    lineHeight: 12,
    marginTop: 2,
  },
  goldButton: {
    height: 46,
    backgroundColor: '#856414',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 1,
    marginTop: 62,
    shadowColor: '#7d641f',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  goldButtonText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 3.3,
  },
  cancelButton: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  cancelText: {
    color: '#c5a86f',
    fontSize: 10,
    letterSpacing: 1,
  },
});