import { Platform, StyleSheet } from 'react-native';

import { palette } from '../constants/palette';

export const styles = StyleSheet.create({
  stage: { flex: 1, backgroundColor: '#343233' },
  keyboard: { flex: 1 },
  scrollShell: { alignItems: 'center', paddingVertical: 28, paddingHorizontal: 14 },
  card: { width: '100%', maxWidth: 360, backgroundColor: palette.paper, padding: 22, minHeight: 620 },
  roomyCard: { paddingHorizontal: 26 },
  dimmed: { opacity: 0.45 },
  header: { alignItems: 'center', marginBottom: 20, paddingTop: 12 },
  compactHeader: { alignItems: 'stretch', marginBottom: 18, paddingTop: 6 },
  headerTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  title: { color: '#050505', fontFamily: Platform.select({ ios: 'Georgia', android: 'serif', default: 'serif' }), fontSize: 29, fontWeight: '800', lineHeight: 31, textAlign: 'center' },
  eyebrow: { color: palette.gold, fontSize: 9, fontWeight: '800', letterSpacing: 1.4, lineHeight: 13, textAlign: 'left' },
  steps: { alignSelf: 'center', flexDirection: 'row', gap: 10, marginTop: 18 },
  stepLine: { width: 42, height: 3, borderRadius: 3, backgroundColor: '#d1d3d4' },
  activeLine: { backgroundColor: palette.gold },
  sectionLabel: { marginTop: 10, marginBottom: 10, color: '#636976', fontSize: 9, letterSpacing: 2.4 },
  inputGroup: { marginBottom: 12 },
  label: { color: '#777', fontSize: 8, letterSpacing: 1.6, marginBottom: 7, fontWeight: '700' },
  inputWrap: { backgroundColor: palette.field, minHeight: 43, flexDirection: 'row', alignItems: 'center' },
  input: { color: palette.ink, flex: 1, minHeight: 43, paddingHorizontal: 12, fontSize: 14, outlineStyle: 'none' },
  inputRight: { paddingRight: 12 },
  eye: { color: palette.muted, fontSize: 18 },
  select: { minHeight: 43, backgroundColor: palette.field, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12, marginBottom: 8 },
  selectText: { color: palette.ink, fontSize: 14 },
  chevron: { color: '#65707f', fontSize: 18 },
  documentRow: { flexDirection: 'row', gap: 10 },
  docBox: { flex: 1, borderStyle: 'dashed', borderColor: '#b7bec8', borderWidth: 1, alignItems: 'center', paddingVertical: 20, minHeight: 98, justifyContent: 'center' },
  docBoxSelected: { borderColor: palette.gold, backgroundColor: '#fbfaf4' },
  docIcon: { fontSize: 23, color: '#69717d', marginBottom: 10 },
  docTitle: { color: palette.ink, fontWeight: '700', fontSize: 12, marginBottom: 5, textAlign: 'center' },
  docHint: { color: '#6f747e', fontSize: 8, textAlign: 'center' },
  buttonRow: { flexDirection: 'row', gap: 16, alignItems: 'center', marginTop: 18 },
  button: { flex: 1, backgroundColor: palette.navy, minHeight: 49, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 },
  wideButton: { width: '100%', flex: 0 },
  dangerButton: { backgroundColor: palette.danger },
  ghostButton: { backgroundColor: 'transparent' },
  pressed: { opacity: 0.72 },
  buttonText: { color: '#fff', fontSize: 10, letterSpacing: 3.2, fontWeight: '800', textAlign: 'center' },
  ghostText: { color: '#9ea4ad' },
  centerShell: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28 },
  caption: { width: '100%', maxWidth: 360, color: '#969696', fontSize: 13, marginBottom: 8 },
  tallCard: { width: '100%', maxWidth: 360, minHeight: 620, backgroundColor: palette.paper, paddingHorizontal: 22, paddingVertical: 38, justifyContent: 'space-between', overflow: 'hidden' },
  pendingContent: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  heroTitle: { fontFamily: Platform.select({ ios: 'Georgia', android: 'serif', default: 'serif' }), fontWeight: '900', fontSize: 31, lineHeight: 31, textAlign: 'center', color: '#020202', marginBottom: 18 },
  heroText: { color: '#676b73', fontSize: 14, lineHeight: 21, textAlign: 'center', marginHorizontal: 14, marginBottom: 18 },
  feedback: { color: palette.gold, textAlign: 'center', fontSize: 12, marginVertical: 10 },
  securityFields: { marginTop: 8 },
  policy: { color: '#9a9da4', fontSize: 9, lineHeight: 13, textAlign: 'center', marginTop: 22, paddingHorizontal: 30 },
  key: { height: 170, width: 260, opacity: 0.045, alignSelf: 'center', marginVertical: 34, position: 'relative' },
  smallKey: { height: 110, transform: [{ scale: 0.86 }], marginVertical: 10 },
  keyCircle: { position: 'absolute', width: 116, height: 116, borderRadius: 58, borderWidth: 24, borderColor: '#061125', left: 0, top: 26, alignItems: 'center', justifyContent: 'center' },
  keyHole: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#061125' },
  keyStem: { position: 'absolute', height: 28, width: 145, backgroundColor: '#061125', left: 100, top: 70 },
  keyToothOne: { position: 'absolute', width: 46, height: 46, backgroundColor: '#061125', left: 170, top: 84, transform: [{ rotate: '45deg' }] },
  keyToothTwo: { position: 'absolute', width: 52, height: 52, backgroundColor: '#061125', left: 218, top: 62, transform: [{ rotate: '45deg' }] },
  profilePanel: { marginTop: 18, backgroundColor: '#fff', paddingHorizontal: 0, paddingTop: 2 },
  profileRow: { borderBottomColor: '#e5e5e5', borderBottomWidth: 1, paddingVertical: 15 },
  profileLabel: { color: palette.gold, fontSize: 8, fontWeight: '800', letterSpacing: 1.5, marginBottom: 7 },
  profileValue: { color: '#111', fontSize: 15, lineHeight: 22 },
  legalBlock: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, backgroundColor: '#f2f2f4', marginHorizontal: -26, paddingHorizontal: 26, paddingVertical: 18 },
  legalText: { flex: 1, color: '#60656f', fontSize: 12, lineHeight: 18 },
  modalStage: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 42 },
  fakeBlur: { flex: 1, minHeight: 360, backgroundColor: '#d9d9d9', marginTop: 22 },
  modalBox: { position: 'absolute', width: '82%', maxWidth: 330, backgroundColor: '#fff', padding: 26, alignItems: 'center', elevation: 12, shadowColor: '#000', shadowOpacity: 0.22, shadowRadius: 20 },
  modalIcon: { color: palette.gold, fontSize: 28, marginBottom: 18 },
  modalText: { fontFamily: Platform.select({ ios: 'Georgia', android: 'serif', default: 'serif' }), color: '#111', fontSize: 18, lineHeight: 27, textAlign: 'center', marginBottom: 22 },
  cancelLink: { paddingTop: 22 },
  cancelText: { color: palette.gold, fontSize: 10, letterSpacing: 3, fontWeight: '800' },
  loadingOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(255,255,255,0.45)', alignItems: 'center', justifyContent: 'center' },
});